server:
  port: 8080

spring:
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    port: 5672


queue:
  twitter: twitter-stream
exchange:
  twitter: twitter-exchange
routing_key:
  track: track.*

twitter:
  url: http://api-stub:8081/api/tweet-api-stub