server:
  port: 9090

spring:
  redis:
    host: redis
    port: 6379
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    port: 5672

queue:
  twitter: twitter-track-hashtag
exchange:
  twitter: twitter-track-exchange
routing_key:
  track: "*"

