server:
  port: 9090

spring:
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

queue:
  twitter: twitter-track-hashtag
exchange:
  twitter: twitter-track-exchange
routing_key:
  track: "*"

info:
  project: "tracked-hashtag-service"
  kotlin: @kotlin.version@
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics